AWSTemplateFormatVersion: "2010-09-09"
Description: Create a role for us to assume and a resource we'll have access to
Parameters:
  BucketName:
    Type: String
    Default: example-sts-uvais-1
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
  STSRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: STSRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::122610487271:user/sts-machine-user
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: s3-access-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource:
                  - !Sub "arn:aws:s3:::${BucketName}"
                  - !Sub "arn:aws:s3:::${BucketName}/*"
