#!/bin/env bash

if [ -z "$1" ]; then
    echo "There has to be a bucket name!"
    exit 1
fi

BUCKET_NAME=$1

echo "=== Deleting objects in bucket $BUCKET_NAME ==="

aws s3 rm \
s3://$BUCKET_NAME \
--recursive