AWSTemplateFormatVersion: "2010-09-09"
Description: Template to launch an EC2 Ubuntu instance to test connecting with EC2 Instance Connect

Parameters:
  ImageId:
    Description: AMI of Ubuntu
    Type: String
    Default: ami-0866a3c8686eaeeba

Resources:
  ExampleInstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"

  ExampleInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: !Ref ImageId
      SecurityGroups:
        - !Ref ExampleInstanceSecurityGroup
      Tags:
        - Value: ExampleInstance
          Key: Name

Outputs:
  InstanceId:
    Description: Instance ID
    Value: !GetAtt ExampleInstance.InstanceId

  InstancePublicIP:
    Description: Public IP address of Instance
    Value: !GetAtt ExampleInstance.PublicIp
